<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>BakuretsuOsakanaKobo.Update</AssemblyName>
    <RootNamespace>BakuretsuOsakanaKobo.Update</RootNamespace>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
